
CREATE TABLE "SPRIDEN"
(	"SPRIDEN_PIDM" NUMBER(8,0) NOT NULL ENABLE,
     "SPRIDEN_ID" VARCHAR2(9 CHAR) NOT NULL ENABLE,
     "SPRIDEN_LAST_NAME" VARCHAR2(60 CHAR) NOT NULL ENABLE,
     "SPRIDEN_FIRST_NAME" VARCHAR2(60 CHAR),
     "SPRIDEN_MI" VARCHAR2(60 CHAR));

CREATE TABLE "SCBCRSE"
(	"SCBCRSE_SUBJ_CODE" VARCHAR2(4 CHAR) NOT NULL ENABLE,
     "SCBCRSE_CRSE_NUMB" VARCHAR2(5 CHAR) NOT NULL ENABLE,
     "SCBCRSE_EFF_TERM" VARCHAR2(6 CHAR),
     "SCBCRSE_TITLE" VARCHAR2(30 CHAR));

CREATE TABLE "STVTERM"
(	"STVTERM_CODE" VARCHAR2(6 CHAR) NOT NULL ENABLE,
     "STVTERM_DESC" VARCHAR2(30 CHAR) NOT NULL ENABLE);

CREATE TABLE "SFRSTCR"
(	"SFRSTCR_TERM_CODE" VARCHAR2(6 CHAR) NOT NULL ENABLE,
     "SFRSTCR_PIDM" NUMBER(8,0) NOT NULL ENABLE,
     "SFRSTCR_CRN" VARCHAR2(5 CHAR) NOT NULL ENABLE,
     "SFRSTCR_RSTS_CODE" VARCHAR2(2 CHAR),
     "SFRSTCR_LEVL_OVER" VARCHAR2(1 CHAR));

CREATE TABLE  "SSBSECT"
(	"SSBSECT_TERM_CODE" VARCHAR2(6 CHAR) NOT NULL ENABLE,
     "SSBSECT_CRN" VARCHAR2(5 CHAR) NOT NULL ENABLE,
     "SSBSECT_PTRM_CODE" VARCHAR2(3 CHAR),
     "SSBSECT_SUBJ_CODE" VARCHAR2(4 CHAR) NOT NULL ENABLE,
     "SSBSECT_CRSE_NUMB" VARCHAR2(5 CHAR) NOT NULL ENABLE,
     "SSBSECT_SEQ_NUMB" VARCHAR2(3 CHAR) NOT NULL ENABLE);

CREATE TABLE "SSRMEET"
(	"SSRMEET_TERM_CODE" VARCHAR2(6 CHAR) NOT NULL ENABLE,
     "SSRMEET_CRN" VARCHAR2(5 CHAR) NOT NULL ENABLE,
     "SSRMEET_BEGIN_TIME" VARCHAR2(4 CHAR),
     "SSRMEET_END_TIME" VARCHAR2(4 CHAR),
     "SSRMEET_MON_DAY" VARCHAR2(1 CHAR),
     "SSRMEET_TUE_DAY" VARCHAR2(1 CHAR),
     "SSRMEET_WED_DAY" VARCHAR2(1 CHAR),
     "SSRMEET_THU_DAY" VARCHAR2(1 CHAR),
     "SSRMEET_FRI_DAY" VARCHAR2(1 CHAR));


CREATE TABLE "SGBSTDN"
(	"SGBSTDN_PIDM" NUMBER(8,0) NOT NULL ENABLE,
     "SGBSTDN_TERM_CODE_EFF" VARCHAR2(6 CHAR) NOT NULL ENABLE,
     "SGBSTDN_STST_CODE" VARCHAR2(2 CHAR) NOT NULL ENABLE,
     "SGBSTDN_LEVL_CODE" VARCHAR2(2 CHAR));

CREATE TABLE "SFRVERF"
(	"SFRVERF_PIDM" NUMBER(8,0),
     "SFRVERF_TERM_CODE" VARCHAR2(6 CHAR),
     "SFRVERF_ACTIVITY_DATE" DATE,
     "SFRVERF_LEVL_CODE" VARCHAR2(4 CHAR),
     "SFRVERF_CANCEL_FLAG" VARCHAR2(1 CHAR));

